spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/logdb?authSource=admin
      database: logdbfile

file: 
  upload-dir: uploads       
  base-url: https://auth.wezd.io.vn/files