spring:

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/product?authSource=admin}

file: 
  upload-dir: ${FILE_UPLOAD_DIR:uploads}
  base-url: ${FILE_BASE_URL:http://localhost:8082/files}