package com.chuadatten.transaction.common;

public enum Status {
    PENDING,
    APPROVED,
    REJECTED,
    EXPIRED,
    SUSPENDED,
    ACTIVE,
    INACTIVE,
    BLOCKED,
    DELETED,
    DISABLED,
    ENABLED,
    UNVERIFIED,
    VERIFIED,
    NONE,
    SUCCESS,
    RETRY, CANCELLED, DELIVERED, OPENED, CREATED, ALREADY_PAYMENT, READY_PAY, PAID, COMPLETED, PROCESSING, PAYING,;


}